import 'dart:math' as math;

import 'package:flutter/widgets.dart';

import '../../painting/base_component_painter.dart';
import '../../painting/path_art.dart';
import '../../models/part_properties.dart';
import 'rgb_led_art.dart';

/// Draws a 5 mm common-cathode RGB LED standing on its four leads, its lens
/// lit in whatever mix of colours is flowing — the body of `rgb_led.pdl`, which
/// names it with `PAINTER rgb_led` and declares everything else: pins, the
/// three-die physics, and the `red`/`green`/`blue` state this reads.
///
/// The artwork is vector paths generated by the Flutter Da Vinci Figma plugin
/// from the "RGB LED" frame in the *PinBench Parts* Figma file — one layer per
/// colour, each shifted to where that layer sits in the frame. Redraw it there
/// and regenerate rather than hand-editing the coordinates. The glow is the one
/// part drawn in code, because it is state rather than artwork.
class RgbLedPainter({final Map<String, dynamic>? properties, super.isOutline})
    extends BaseComponentPainter
    with PathArtPainter {
  // The `SIZE` the .pdl declares: the leads' tips one hole pitch apart on the
  // lattice where its pins are, the dome centred over them.
  static const width = 56.0;
  static const height = 72.0;
  static const componentSize = Size(width, height);

  /// The dome and its flange; the leads below are what the pins reach for.
  @override
  Rect bodyRect(Size size) => const Rect.fromLTWH(17.1, 4, 23, 36);

  @override
  Size get designSize => componentSize;

  @override
  List<PathArtLayer> get layers => _layers;

  static final _layers = <PathArtLayer>[
    (RgbLedArt.metal, const Color(0xFF8C8C8C)),
    (RgbLedArt.lens, const Color(0x59FFFFFF)),
    (RgbLedArt.outline, const Color(0xCC888888)),
  ];

  /// A colour's brightness, 0–1, as the `led_array` logic last wrote it.
  double _level(String colour) => properties.level(colour);

  @override
  void paintOverlay(Canvas canvas) {
    final red = _level('red');
    final green = _level('green');
    final blue = _level('blue');
    final peak = math.max(red, math.max(green, blue));
    if (peak == 0) return;

    // The hue from the ratio of the three, the strength from the brightest:
    // a dim red is a faint red, not a dark one.
    final colour = Color.from(alpha: 1, red: red / peak, green: green / peak, blue: blue / peak);
    canvas.drawCircle(
      const Offset(28, 16),
      14,
      Paint()
        ..color = colour.withValues(alpha: 0.6 * peak)
        ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 8),
    );
    final tint = Paint()..color = colour.withValues(alpha: 0.7 * peak);
    for (final path in RgbLedArt.lens) {
      canvas.drawPath(path, tint);
    }
  }
}
