import 'package:flutter/widgets.dart';

import '../painting/base_component_painter.dart';
import '../painting/path_art.dart';

/// Which axial diode an [AxialDiodePainter] draws.
enum DiodeKind() {
  /// A 1N4007: black moulded DO-41 body, grey band.
  rectifier,

  /// A 1N4148: orange die in clear glass, black band.
  switching,

  /// A 1N5819: the rectifier's DO-41 body with a silver band.
  schottky,
}

/// Draws an axial diode standing on its leads, anode up and the cathode band
/// toward the bottom — the body of the `diode_*.pdl` parts, which name it with
/// `PAINTER diode_<part number>` and declare everything else: pins and physics.
///
/// The artwork is vector paths generated by the Flutter Da Vinci Figma plugin
/// from the "Diode 1N4007", "Diode 1N4148 glass" and "Diode 1N5819" frames in
/// the *PinBench Parts* Figma file — one layer per colour, each shifted to
/// where that layer sits in the frame. All three share the leads, the body's
/// box and the band's place, so they read as one family; only the materials
/// differ by [kind]. Redraw them there and regenerate rather than hand-editing
/// the coordinates.
class AxialDiodePainter(
  final DiodeKind kind, {
  final Map<String, dynamic>? properties,
  super.isOutline,
}) extends BaseComponentPainter with PathArtPainter {
  // The `SIZE` the .pdl declares: the leads' tips four hole pitches apart on
  // the lattice where its pins are, the body centred between them.
  static const width = 40.0;
  static const height = 72.0;
  static const componentSize = Size(width, height);

  /// The body; the leads beyond it are what the pins reach for.
  @override
  Rect bodyRect(Size size) => const Rect.fromLTWH(12.73, 17.02, 14.54, 37.97);

  @override
  Size get designSize => componentSize;

  @override
  List<PathArtLayer> get layers => switch (kind) {
    DiodeKind.rectifier => _rectifier,
    DiodeKind.switching => _switching,
    DiodeKind.schottky => _schottky,
  };

  static final _rectifier = <PathArtLayer>[
    (_leads, const Color(0xFF8C8C8C)),
    (_body, const Color(0xFF333333)),
    (_cathodeBand, const Color(0xFF6A757E)),
  ];

  static final _switching = <PathArtLayer>[
    (_leads, const Color(0xFF8C8C8C)),
    (_glass, const Color(0xB2B8C4CA)),
    (_glassCore, const Color(0xFFD9622B)),
    (_cathodeBand, const Color(0xFF2A2A2A)),
  ];

  static final _schottky = <PathArtLayer>[
    (_leads, const Color(0xFF8C8C8C)),
    (_body, const Color(0xFF333333)),
    (_cathodeBand, const Color(0xFFC8C8C8)),
  ];

  /// The leads, one wire through the body.
  static final _leads = PathArtPainter.layer(const Offset(18.3729, 4), [
    Path()
      ..moveTo(0, 1.63)
      ..cubicTo(0, 0.73, 0.73, 0, 1.63, 0)
      ..cubicTo(2.53, 0, 3.25, 0.73, 3.25, 1.63)
      ..lineTo(3.25, 62.37)
      ..cubicTo(3.25, 63.27, 2.53, 64, 1.63, 64)
      ..cubicTo(0.73, 64, 0, 63.27, 0, 62.37)
      ..lineTo(0, 1.63)
      ..close(),
  ]);

  /// The moulded body of a DO-41 rectifier or Schottky.
  static final _body = PathArtPainter.layer(const Offset(12.7322, 17.017), [
    Path()
      ..moveTo(0, 1.08)
      ..cubicTo(0, 0.49, 0.49, 0, 1.08, 0)
      ..lineTo(13.45, 0)
      ..cubicTo(14.05, 0, 14.54, 0.49, 14.54, 1.08)
      ..lineTo(14.54, 36.88)
      ..cubicTo(14.54, 37.48, 14.05, 37.97, 13.45, 37.97)
      ..lineTo(1.08, 37.97)
      ..cubicTo(0.49, 37.97, 0, 37.48, 0, 36.88)
      ..lineTo(0, 1.08)
      ..close(),
  ]);

  /// The cathode band, at the end nearer the cathode pin — the same place on
  /// every kind, in each kind's colour.
  static final _cathodeBand = PathArtPainter.layer(const Offset(12.7322, 44.3525), [
    Path()
      ..moveTo(0, 0)
      ..lineTo(14.54, 0)
      ..lineTo(14.54, 3.47)
      ..lineTo(0, 3.47)
      ..lineTo(0, 0)
      ..close(),
  ]);

  /// The 1N4148's clear glass envelope, the leads showing through it.
  static final _glass = PathArtPainter.layer(const Offset(12.7322, 17.017), [
    Path()
      ..moveTo(0, 1.08)
      ..cubicTo(0, 0.48, 0.48, 0, 1.08, 0)
      ..lineTo(13.46, 0)
      ..cubicTo(14.05, 0, 14.54, 0.48, 14.54, 1.08)
      ..lineTo(14.54, 36.89)
      ..cubicTo(14.54, 37.48, 14.05, 37.97, 13.46, 37.97)
      ..lineTo(1.08, 37.97)
      ..cubicTo(0.48, 37.97, 0, 37.48, 0, 36.89)
      ..lineTo(0, 1.08)
      ..close(),
  ]);

  /// The orange-coated die inside the glass, short of both ends.
  static final _glassCore = PathArtPainter.layer(const Offset(13.9322, 20.217), [
    Path()
      ..moveTo(0, 0.8)
      ..cubicTo(0, 0.36, 0.36, 0, 0.8, 0)
      ..lineTo(11.34, 0)
      ..cubicTo(11.78, 0, 12.14, 0.36, 12.14, 0.8)
      ..lineTo(12.14, 30.77)
      ..cubicTo(12.14, 31.21, 11.78, 31.57, 11.34, 31.57)
      ..lineTo(0.8, 31.57)
      ..cubicTo(0.36, 31.57, 0, 31.21, 0, 30.77)
      ..lineTo(0, 0.8)
      ..close(),
  ]);
}
