import 'package:flutter/widgets.dart';

import '../painting/base_component_painter.dart';
import '../painting/grid_system.dart';
import '../painting/path_art.dart';
import '../painting/port_provider.dart';
import '../models/port_model.dart';

/// Draws a 9 V PP3 battery with its snap clip, leads exiting to the left.
///
/// The artwork is vector paths generated by the Flutter Da Vinci Figma plugin
/// from the "Battery 9V" frame in the *PinBench Parts* Figma file — one layer
/// per colour, each shifted to where that layer sits in the frame. Redraw it
/// there and regenerate rather than hand-editing the coordinates.
///
/// Electrically an ideal source (see its entry in `standardParts`): it does not
/// sag under load or run down.
class Battery9vPainter({final Map<String, dynamic>? properties, super.isOutline})
    extends BaseComponentPainter
    with PortProvider, PathArtPainter {
  // The PP3 case is 48.5 × 26.5 mm; the footprint is rounded to whole hole
  // pitches (19 × 10) so both lead tips land on the connection lattice.
  static const width = 19 * GridSystem.pitch;
  static const height = 10 * GridSystem.pitch;
  static const componentSize = Size(width, height);

  // Lead tips, one hole pitch apart: black (−) above red (+).
  static const leadTipX = GridSystem.cellCenter;
  static const minusY = 4 * GridSystem.pitch + GridSystem.cellCenter;
  static const plusY = 5 * GridSystem.pitch + GridSystem.cellCenter;

  /// The case and clip; the leads hang off it to the ports.
  @override
  Rect bodyRect(Size size) => const Rect.fromLTRB(24, 8, width, 152);

  @override
  List<ComponentPort> getPorts() => const [
    ComponentPort(id: 'plus', name: '+', localOffset: Offset(leadTipX, plusY)),
    ComponentPort(id: 'minus', name: '-', localOffset: Offset(leadTipX, minusY)),
  ];

  @override
  Size get designSize => componentSize;

  @override
  List<PathArtLayer> get layers => _layers;

  static final _layers = <PathArtLayer>[
    (_copper, const Color(0xFFCB804F)),
    (_polarityRings, const Color(0xFFAB6F48)),
    (_dark, const Color(0xFF2D2D2D)),
    (_terminalShadow, const Color(0xFF818181)),
    (_terminalFace, const Color(0xFFB1B1B1)),
    (_redLead, const Color(0xFFA5161F)),
    (_label, const Color(0xFFD8D8D8)),
  ];

  /// Copper cap over the terminal end.
  static final _copper = PathArtPainter.layer(const Offset(60, 8), [
    Path()
      ..moveTo(0, 5)
      ..cubicTo(0, 2.24, 2.24, 0, 5, 0)
      ..lineTo(74, 0)
      ..lineTo(74, 144)
      ..lineTo(5, 144)
      ..cubicTo(2.24, 144, 0, 141.76, 0, 139)
      ..lineTo(0, 5)
      ..close(),
  ]);

  /// Embossed rings around the polarity marks.
  static final _polarityRings = PathArtPainter.layer(const Offset(63.5, 37.5), [
    Path()
      ..moveTo(15.7, 8.5)
      ..cubicTo(15.7, 4.52, 12.48, 1.3, 8.5, 1.3)
      ..cubicTo(4.52, 1.3, 1.3, 4.52, 1.3, 8.5)
      ..cubicTo(1.3, 12.48, 4.52, 15.7, 8.5, 15.7)
      ..lineTo(8.5, 17)
      ..cubicTo(3.81, 17, 0, 13.19, 0, 8.5)
      ..cubicTo(0, 3.81, 3.81, 0, 8.5, 0)
      ..cubicTo(13.19, 0, 17, 3.81, 17, 8.5)
      ..cubicTo(17, 13.19, 13.19, 17, 8.5, 17)
      ..lineTo(8.5, 15.7)
      ..cubicTo(12.48, 15.7, 15.7, 12.48, 15.7, 8.5)
      ..close(),
    Path()
      ..moveTo(15.7, 71.5)
      ..cubicTo(15.7, 67.52, 12.48, 64.3, 8.5, 64.3)
      ..cubicTo(4.52, 64.3, 1.3, 67.52, 1.3, 71.5)
      ..cubicTo(1.3, 75.48, 4.52, 78.7, 8.5, 78.7)
      ..lineTo(8.5, 80)
      ..cubicTo(3.81, 80, 0, 76.19, 0, 71.5)
      ..cubicTo(0, 66.81, 3.81, 63, 8.5, 63)
      ..cubicTo(13.19, 63, 17, 66.81, 17, 71.5)
      ..cubicTo(17, 76.19, 13.19, 80, 8.5, 80)
      ..lineTo(8.5, 78.7)
      ..cubicTo(12.48, 78.7, 15.7, 75.48, 15.7, 71.5)
      ..close(),
  ]);

  /// Body wrap, snap clip, black lead and the polarity marks.
  static final _dark = PathArtPainter.layer(const Offset(8, 8), [
    Path()
      ..moveTo(126, 0)
      ..lineTo(291, 0)
      ..cubicTo(293.76, 0, 296, 2.24, 296, 5)
      ..lineTo(296, 139)
      ..cubicTo(296, 141.76, 293.76, 144, 291, 144)
      ..lineTo(126, 144)
      ..lineTo(126, 0)
      ..close(),
    Path()
      ..moveTo(16, 7)
      ..cubicTo(16, 5.34, 17.34, 4, 19, 4)
      ..lineTo(25, 4)
      ..cubicTo(26.66, 4, 28, 5.34, 28, 7)
      ..lineTo(28, 137)
      ..cubicTo(28, 138.66, 26.66, 140, 25, 140)
      ..lineTo(19, 140)
      ..cubicTo(17.34, 140, 16, 138.66, 16, 137)
      ..lineTo(16, 7)
      ..close(),
    Path()
      ..moveTo(0, 58.5)
      ..cubicTo(0, 57.4, 0.9, 56.5, 2, 56.5)
      ..lineTo(9, 56.5)
      ..cubicTo(10.1, 56.5, 11, 57.4, 11, 58.5)
      ..lineTo(11, 61.5)
      ..cubicTo(11, 62.6, 10.1, 63.5, 9, 63.5)
      ..lineTo(2, 63.5)
      ..cubicTo(0.9, 63.5, 0, 62.6, 0, 61.5)
      ..lineTo(0, 58.5)
      ..close(),
    Path()
      ..moveTo(63.2, 34.3)
      ..cubicTo(63.2, 33.86, 63.56, 33.5, 64, 33.5)
      ..cubicTo(64.44, 33.5, 64.8, 33.86, 64.8, 34.3)
      ..lineTo(64.8, 41.7)
      ..cubicTo(64.8, 42.14, 64.44, 42.5, 64, 42.5)
      ..cubicTo(63.56, 42.5, 63.2, 42.14, 63.2, 41.7)
      ..lineTo(63.2, 34.3)
      ..close(),
    Path()
      ..moveTo(63.2, 97.3)
      ..cubicTo(63.2, 96.86, 63.56, 96.5, 64, 96.5)
      ..cubicTo(64.44, 96.5, 64.8, 96.86, 64.8, 97.3)
      ..lineTo(64.8, 104.7)
      ..cubicTo(64.8, 105.14, 64.44, 105.5, 64, 105.5)
      ..cubicTo(63.56, 105.5, 63.2, 105.14, 63.2, 104.7)
      ..lineTo(63.2, 97.3)
      ..close(),
    Path()
      ..moveTo(59.5, 101)
      ..cubicTo(59.5, 100.56, 59.86, 100.2, 60.3, 100.2)
      ..lineTo(67.7, 100.2)
      ..cubicTo(68.14, 100.2, 68.5, 100.56, 68.5, 101)
      ..cubicTo(68.5, 101.44, 68.14, 101.8, 67.7, 101.8)
      ..lineTo(60.3, 101.8)
      ..cubicTo(59.86, 101.8, 59.5, 101.44, 59.5, 101)
      ..close(),
    Path()
      ..moveTo(10, 58.25)
      ..cubicTo(12.01, 58.25, 13.13, 58.99, 13.99, 59.48)
      ..cubicTo(14.69, 59.88, 15.39, 60.25, 17, 60.25)
      ..lineTo(17, 63.75)
      ..cubicTo(14.61, 63.75, 13.31, 63.12, 12.26, 62.52)
      ..cubicTo(11.37, 62.01, 10.99, 61.75, 10, 61.75)
      ..lineTo(10, 58.25)
      ..close(),
  ]);

  /// Terminal shoulders and the lead pin tips.
  static final _terminalShadow = PathArtPainter.layer(const Offset(0, 26), [
    Path()
      ..moveTo(36, 1)
      ..cubicTo(36, 0.45, 36.45, 0, 37, 0)
      ..lineTo(43, 0)
      ..cubicTo(43.55, 0, 44, 0.45, 44, 1)
      ..lineTo(44, 40)
      ..cubicTo(44, 40.55, 43.55, 41, 43, 41)
      ..lineTo(37, 41)
      ..cubicTo(36.45, 41, 36, 40.55, 36, 40)
      ..lineTo(36, 1)
      ..close(),
    Path()
      ..moveTo(36, 60)
      ..cubicTo(36, 58.9, 36.9, 58, 38, 58)
      ..lineTo(51, 58)
      ..cubicTo(52.1, 58, 53, 58.9, 53, 60)
      ..lineTo(53, 106)
      ..cubicTo(53, 107.1, 52.1, 108, 51, 108)
      ..lineTo(38, 108)
      ..cubicTo(36.9, 108, 36, 107.1, 36, 106)
      ..lineTo(36, 60)
      ..close(),
    Path()
      ..moveTo(0, 42)
      ..cubicTo(0, 41.17, 0.67, 40.5, 1.5, 40.5)
      ..lineTo(7.5, 40.5)
      ..cubicTo(8.33, 40.5, 9, 41.17, 9, 42)
      ..cubicTo(9, 42.83, 8.33, 43.5, 7.5, 43.5)
      ..lineTo(1.5, 43.5)
      ..cubicTo(0.67, 43.5, 0, 42.83, 0, 42)
      ..close(),
    Path()
      ..moveTo(0, 58)
      ..cubicTo(0, 57.17, 0.67, 56.5, 1.5, 56.5)
      ..lineTo(7.5, 56.5)
      ..cubicTo(8.33, 56.5, 9, 57.17, 9, 58)
      ..cubicTo(9, 58.83, 8.33, 59.5, 7.5, 59.5)
      ..lineTo(1.5, 59.5)
      ..cubicTo(0.67, 59.5, 0, 58.83, 0, 58)
      ..close(),
  ]);

  /// Terminal faces.
  static final _terminalFace = PathArtPainter.layer(const Offset(44, 22), [
    Path()
      ..moveTo(0, 2)
      ..cubicTo(0, 0.9, 0.9, 0, 2, 0)
      ..lineTo(16, 0)
      ..lineTo(16, 49)
      ..lineTo(2, 49)
      ..cubicTo(0.9, 49, 0, 48.1, 0, 47)
      ..lineTo(0, 2)
      ..close(),
    Path()
      ..moveTo(9, 66)
      ..lineTo(16, 66)
      ..lineTo(16, 108)
      ..lineTo(9, 108)
      ..lineTo(9, 66)
      ..close(),
  ]);

  /// Red (+) lead.
  static final _redLead = PathArtPainter.layer(const Offset(8, 80.25), [
    Path()
      ..moveTo(0, 2.25)
      ..cubicTo(0, 1.15, 0.9, 0.25, 2, 0.25)
      ..lineTo(9, 0.25)
      ..cubicTo(10.1, 0.25, 11, 1.15, 11, 2.25)
      ..lineTo(11, 5.25)
      ..cubicTo(11, 6.35, 10.1, 7.25, 9, 7.25)
      ..lineTo(2, 7.25)
      ..cubicTo(0.9, 7.25, 0, 6.35, 0, 5.25)
      ..lineTo(0, 2.25)
      ..close(),
    Path()
      ..moveTo(17, 3.5)
      ..cubicTo(15.39, 3.5, 14.69, 3.87, 13.99, 4.27)
      ..cubicTo(13.13, 4.76, 12.01, 5.5, 10, 5.5)
      ..lineTo(10, 2)
      ..cubicTo(10.99, 2, 11.37, 1.74, 12.26, 1.23)
      ..cubicTo(13.31, 0.63, 14.61, 0, 17, 0)
      ..lineTo(17, 3.5)
      ..close(),
  ]);

  /// The "9V" legend, reading bottom to top.
  static final _label = PathArtPainter.layer(const Offset(188.47, 53.4976), [
    Path()
      ..moveTo(30.45, 44.21)
      ..cubicTo(30.45, 45.42, 30.27, 46.66, 29.9, 47.95)
      ..cubicTo(29.51, 49.24, 28.94, 50.44, 28.18, 51.56)
      ..cubicTo(27.9, 52.01, 27.54, 52.3, 27.09, 52.44)
      ..cubicTo(26.64, 52.58, 26.21, 52.61, 25.79, 52.53)
      ..cubicTo(25.34, 52.42, 24.96, 52.22, 24.65, 51.94)
      ..cubicTo(24.32, 51.63, 24.12, 51.25, 24.07, 50.81)
      ..cubicTo(23.98, 50.36, 24.09, 49.87, 24.4, 49.34)
      ..cubicTo(24.96, 48.38, 25.35, 47.49, 25.58, 46.65)
      ..cubicTo(25.8, 45.81, 25.91, 44.97, 25.91, 44.13)
      ..cubicTo(25.91, 42.5, 25.54, 41.13, 24.78, 40.01)
      ..cubicTo(24.02, 38.89, 22.89, 38.05, 21.38, 37.49)
      ..cubicTo(19.84, 36.9, 17.95, 36.61, 15.71, 36.61)
      ..lineTo(12.56, 36.61)
      ..lineTo(12.56, 36.11)
      ..cubicTo(13.96, 36.3, 15.18, 36.76, 16.21, 37.49)
      ..cubicTo(17.25, 38.22, 18.05, 39.14, 18.61, 40.26)
      ..cubicTo(19.14, 41.38, 19.4, 42.63, 19.4, 44)
      ..cubicTo(19.4, 45.68, 19, 47.19, 18.19, 48.54)
      ..cubicTo(17.37, 49.85, 16.25, 50.89, 14.83, 51.65)
      ..cubicTo(13.37, 52.4, 11.73, 52.78, 9.91, 52.78)
      ..cubicTo(7.98, 52.78, 6.27, 52.37, 4.79, 51.56)
      ..cubicTo(3.3, 50.72, 2.14, 49.56, 1.3, 48.08)
      ..cubicTo(0.43, 46.59, -0, 44.9, 0, 42.99)
      ..cubicTo(0, 40.53, 0.57, 38.44, 1.72, 36.74)
      ..cubicTo(2.87, 35.03, 4.55, 33.73, 6.76, 32.83)
      ..cubicTo(8.95, 31.93, 11.59, 31.49, 14.7, 31.49)
      ..cubicTo(17.22, 31.49, 19.46, 31.78, 21.42, 32.37)
      ..cubicTo(23.35, 32.93, 24.99, 33.75, 26.33, 34.85)
      ..cubicTo(27.68, 35.94, 28.7, 37.28, 29.4, 38.88)
      ..cubicTo(30.1, 40.45, 30.45, 42.22, 30.45, 44.21)
      ..close()
      ..moveTo(15.12, 42.66)
      ..cubicTo(15.12, 41.65, 14.9, 40.77, 14.45, 40.01)
      ..cubicTo(13.97, 39.23, 13.33, 38.63, 12.52, 38.21)
      ..cubicTo(11.68, 37.79, 10.72, 37.58, 9.66, 37.58)
      ..cubicTo(8.57, 37.58, 7.62, 37.79, 6.8, 38.21)
      ..cubicTo(5.99, 38.63, 5.36, 39.23, 4.91, 40.01)
      ..cubicTo(4.47, 40.77, 4.24, 41.65, 4.24, 42.66)
      ..cubicTo(4.24, 43.67, 4.47, 44.55, 4.91, 45.3)
      ..cubicTo(5.36, 46.06, 5.99, 46.66, 6.8, 47.11)
      ..cubicTo(7.62, 47.53, 8.57, 47.74, 9.66, 47.74)
      ..cubicTo(10.72, 47.74, 11.68, 47.53, 12.52, 47.11)
      ..cubicTo(13.33, 46.66, 13.97, 46.06, 14.45, 45.3)
      ..cubicTo(14.9, 44.55, 15.12, 43.67, 15.12, 42.66)
      ..close(),
    Path()
      ..moveTo(30.37, 14.32)
      ..cubicTo(30.37, 15.08, 30.2, 15.71, 29.86, 16.21)
      ..cubicTo(29.5, 16.69, 28.97, 17.08, 28.27, 17.39)
      ..lineTo(3.65, 28.35)
      ..cubicTo(2.95, 28.66, 2.34, 28.74, 1.81, 28.6)
      ..cubicTo(1.27, 28.46, 0.85, 28.17, 0.55, 27.72)
      ..cubicTo(0.24, 27.27, 0.08, 26.74, 0.08, 26.13)
      ..cubicTo(0.08, 25.31, 0.27, 24.71, 0.63, 24.32)
      ..cubicTo(0.97, 23.9, 1.48, 23.55, 2.18, 23.27)
      ..lineTo(25.24, 13.32)
      ..lineTo(25.24, 15.12)
      ..lineTo(2.14, 5.21)
      ..cubicTo(1.47, 4.9, 0.97, 4.54, 0.63, 4.12)
      ..cubicTo(0.27, 3.7, 0.08, 3.11, 0.08, 2.35)
      ..cubicTo(0.08, 1.74, 0.24, 1.23, 0.55, 0.84)
      ..cubicTo(0.85, 0.42, 1.27, 0.16, 1.81, 0.04)
      ..cubicTo(2.34, -0.07, 2.95, 0.03, 3.65, 0.34)
      ..lineTo(28.27, 11.3)
      ..cubicTo(28.97, 11.61, 29.5, 12, 29.86, 12.48)
      ..cubicTo(30.2, 12.92, 30.37, 13.54, 30.37, 14.32)
      ..close(),
  ]);
}
