import 'package:flutter/widgets.dart';

import '../painting/base_component_painter.dart';
import '../painting/path_art.dart';

/// Draws a 1N4148 in its DO-35 package standing on its leads, anode up and the
/// cathode band toward the bottom — the body of `diode_1n4148.pdl`, which
/// names it with `PAINTER diode_1n4148` and declares everything else: pins and
/// physics.
///
/// The artwork is vector paths generated by the Flutter Da Vinci Figma plugin
/// from the "Diode 1N4148" frame in the *PinBench Parts* Figma file — one
/// layer per colour, each shifted to where that layer sits in the frame.
/// Redraw it there and regenerate rather than hand-editing the coordinates.
class Diode1n4148Painter({final Map<String, dynamic>? properties, super.isOutline})
    extends BaseComponentPainter
    with PathArtPainter {
  // The `SIZE` the .pdl declares: the leads' tips four hole pitches apart on
  // the lattice where its pins are, the body centred between them.
  static const width = 40.0;
  static const height = 72.0;
  static const componentSize = Size(width, height);

  /// The body; the leads beyond it are what the pins reach for.
  @override
  Rect bodyRect(Size size) => const Rect.fromLTWH(12.73, 17.02, 14.54, 37.97);

  @override
  Size get designSize => componentSize;

  @override
  List<PathArtLayer> get layers => _layers;

  static final _layers = <PathArtLayer>[
    (_leads, const Color(0xFF8C8C8C)),
    (_body, const Color(0xFF333333)),
    (_cathodeBand, const Color(0xFF6A757E)),
  ];

  /// The leads, one wire through the body.
  static final _leads = PathArtPainter.layer(const Offset(18.3729, 4), [
    Path()
      ..moveTo(0, 1.63)
      ..cubicTo(0, 0.73, 0.73, 0, 1.63, 0)
      ..cubicTo(2.53, 0, 3.25, 0.73, 3.25, 1.63)
      ..lineTo(3.25, 62.37)
      ..cubicTo(3.25, 63.27, 2.53, 64, 1.63, 64)
      ..cubicTo(0.73, 64, 0, 63.27, 0, 62.37)
      ..lineTo(0, 1.63)
      ..close(),
  ]);

  /// The body.
  static final _body = PathArtPainter.layer(const Offset(12.7322, 17.017), [
    Path()
      ..moveTo(0, 1.08)
      ..cubicTo(0, 0.49, 0.49, 0, 1.08, 0)
      ..lineTo(13.45, 0)
      ..cubicTo(14.05, 0, 14.54, 0.49, 14.54, 1.08)
      ..lineTo(14.54, 36.88)
      ..cubicTo(14.54, 37.48, 14.05, 37.97, 13.45, 37.97)
      ..lineTo(1.08, 37.97)
      ..cubicTo(0.49, 37.97, 0, 37.48, 0, 36.88)
      ..lineTo(0, 1.08)
      ..close(),
  ]);

  /// Cathode band, at the end nearer the cathode pin.
  static final _cathodeBand = PathArtPainter.layer(const Offset(12.7322, 44.3525), [
    Path()
      ..moveTo(0, 0)
      ..lineTo(14.54, 0)
      ..lineTo(14.54, 3.47)
      ..lineTo(0, 3.47)
      ..lineTo(0, 0)
      ..close(),
  ]);
}
