import 'package:flutter/widgets.dart';

import '../painting/base_component_painter.dart';
import '../painting/path_art.dart';

/// Draws a 0.56-inch common-cathode 7-segment display, each segment lit as
/// brightly as the current through it — the body of `seven_segment.pdl`, which
/// names it with `PAINTER seven_segment` and declares everything else: the ten
/// pins, the eight-die physics, and the per-segment state this reads.
///
/// The artwork is vector paths generated by the Flutter Da Vinci Figma plugin
/// from the "7-Segment Display" frame in the *PinBench Parts* Figma file —
/// one layer per segment, so each can light on its own. Redraw it there and
/// regenerate rather than hand-editing the coordinates. The glow is drawn in
/// code, because it is state rather than artwork.
class SevenSegmentPainter({final Map<String, dynamic>? properties, super.isOutline})
    extends BaseComponentPainter
    with PathArtPainter {
  // The `SIZE` the .pdl declares: two rows of five pins one hole pitch apart,
  // six pitches between the rows — a real 0.56-inch display's footprint.
  static const width = 104.0;
  static const height = 136.0;
  static const componentSize = Size(width, height);

  static const _unlit = Color(0xFFB2B2B2);
  static const _lit = Color(0xFFFF3B30);

  /// The body; the pins are under it, as on the real part.
  @override
  Rect bodyRect(Size size) => const Rect.fromLTWH(12.21, 8.14, 79.8, 119.9);

  @override
  Size get designSize => componentSize;

  @override
  List<PathArtLayer> get layers => _layers;

  static final _layers = <PathArtLayer>[
    (_body, const Color(0xFF3D4042)),
    (_pinMarks, const Color(0xFF515355)),
    for (final (_, paths) in _segments) (paths, _unlit),
  ];

  /// Each segment's paths under the pin — and state — id it answers to.
  static final _segments = <(String, List<Path>)>[
    ('a', _segA),
    ('b', _segB),
    ('c', _segC),
    ('d', _segD),
    ('e', _segE),
    ('f', _segF),
    ('g', _segG),
    ('dp', _segDp),
  ];

  /// A segment's brightness, 0–1, as the `led_array` logic last wrote it.
  double _level(String segment) => switch (properties?[segment]) {
    final num n => n.toDouble().clamp(0, 1),
    final String s => (double.tryParse(s) ?? 0).clamp(0, 1),
    _ => 0,
  };

  @override
  void paintComponent(Canvas canvas, Size size) {
    super.paintComponent(canvas, size);
    if (isOutline) return;

    canvas.save();
    canvas.scale(size.width / width, size.height / height);
    for (final (segment, paths) in _segments) {
      final level = _level(segment);
      if (level == 0) continue;
      final glow = Paint()
        ..color = _lit.withValues(alpha: 0.6 * level)
        ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 3);
      final face = Paint()..color = Color.lerp(_unlit, _lit, 0.4 + 0.6 * level)!;
      for (final path in paths) {
        canvas.drawPath(path, glow);
        canvas.drawPath(path, face);
      }
    }
    canvas.restore();
  }

  /// The moulded body.
  static final _body = PathArtPainter.layer(const Offset(12.209, 8.1425), [
    Path()
      ..moveTo(0, 2.74)
      ..cubicTo(0, 1.23, 1.23, 0, 2.74, 0)
      ..lineTo(77.07, 0)
      ..cubicTo(78.58, 0, 79.81, 1.23, 79.81, 2.74)
      ..lineTo(79.81, 117.21)
      ..cubicTo(79.81, 118.72, 78.58, 119.94, 77.07, 119.94)
      ..lineTo(2.74, 119.94)
      ..cubicTo(1.23, 119.94, 0, 118.72, 0, 117.21)
      ..lineTo(0, 2.74)
      ..close(),
  ]);

  /// Where the ten pins come through, two rows of five.
  static final _pinMarks = PathArtPainter.layer(const Offset(17.6818, 17.6057), [
    Path()
      ..moveTo(4.79, 2.39)
      ..cubicTo(4.79, 3.72, 3.72, 4.79, 2.39, 4.79)
      ..cubicTo(1.07, 4.79, 0, 3.72, 0, 2.39)
      ..cubicTo(0, 1.07, 1.07, 0, 2.39, 0)
      ..cubicTo(3.72, 0, 4.79, 1.07, 4.79, 2.39)
      ..close(),
    Path()
      ..moveTo(20.75, 2.39)
      ..cubicTo(20.75, 3.72, 19.68, 4.79, 18.36, 4.79)
      ..cubicTo(17.03, 4.79, 15.96, 3.72, 15.96, 2.39)
      ..cubicTo(15.96, 1.07, 17.03, 0, 18.36, 0)
      ..cubicTo(19.68, 0, 20.75, 1.07, 20.75, 2.39)
      ..close(),
    Path()
      ..moveTo(36.71, 2.39)
      ..cubicTo(36.71, 3.72, 35.64, 4.79, 34.32, 4.79)
      ..cubicTo(33, 4.79, 31.92, 3.72, 31.92, 2.39)
      ..cubicTo(31.92, 1.07, 33, 0, 34.32, 0)
      ..cubicTo(35.64, 0, 36.71, 1.07, 36.71, 2.39)
      ..close(),
    Path()
      ..moveTo(52.67, 2.39)
      ..cubicTo(52.67, 3.72, 51.6, 4.79, 50.28, 4.79)
      ..cubicTo(48.96, 4.79, 47.89, 3.72, 47.89, 2.39)
      ..cubicTo(47.89, 1.07, 48.96, 0, 50.28, 0)
      ..cubicTo(51.6, 0, 52.67, 1.07, 52.67, 2.39)
      ..close(),
    Path()
      ..moveTo(68.64, 2.39)
      ..cubicTo(68.64, 3.72, 67.56, 4.79, 66.24, 4.79)
      ..cubicTo(64.92, 4.79, 63.85, 3.72, 63.85, 2.39)
      ..cubicTo(63.85, 1.07, 64.92, 0, 66.24, 0)
      ..cubicTo(67.56, 0, 68.64, 1.07, 68.64, 2.39)
      ..close(),
    Path()
      ..moveTo(4.79, 98.39)
      ..cubicTo(4.79, 99.72, 3.72, 100.79, 2.39, 100.79)
      ..cubicTo(1.07, 100.79, 0, 99.72, 0, 98.39)
      ..cubicTo(0, 97.07, 1.07, 96, 2.39, 96)
      ..cubicTo(3.72, 96, 4.79, 97.07, 4.79, 98.39)
      ..close(),
    Path()
      ..moveTo(20.75, 98.39)
      ..cubicTo(20.75, 99.72, 19.68, 100.79, 18.36, 100.79)
      ..cubicTo(17.03, 100.79, 15.96, 99.72, 15.96, 98.39)
      ..cubicTo(15.96, 97.07, 17.03, 96, 18.36, 96)
      ..cubicTo(19.68, 96, 20.75, 97.07, 20.75, 98.39)
      ..close(),
    Path()
      ..moveTo(36.71, 98.39)
      ..cubicTo(36.71, 99.72, 35.64, 100.79, 34.32, 100.79)
      ..cubicTo(33, 100.79, 31.92, 99.72, 31.92, 98.39)
      ..cubicTo(31.92, 97.07, 33, 96, 34.32, 96)
      ..cubicTo(35.64, 96, 36.71, 97.07, 36.71, 98.39)
      ..close(),
    Path()
      ..moveTo(52.67, 98.39)
      ..cubicTo(52.67, 99.72, 51.6, 100.79, 50.28, 100.79)
      ..cubicTo(48.96, 100.79, 47.89, 99.72, 47.89, 98.39)
      ..cubicTo(47.89, 97.07, 48.96, 96, 50.28, 96)
      ..cubicTo(51.6, 96, 52.67, 97.07, 52.67, 98.39)
      ..close(),
    Path()
      ..moveTo(68.64, 98.39)
      ..cubicTo(68.64, 99.72, 67.56, 100.79, 66.24, 100.79)
      ..cubicTo(64.92, 100.79, 63.85, 99.72, 63.85, 98.39)
      ..cubicTo(63.85, 97.07, 64.92, 96, 66.24, 96)
      ..cubicTo(67.56, 96, 68.64, 97.07, 68.64, 98.39)
      ..close(),
  ]);

  /// Segment a.
  static final _segA = PathArtPainter.layer(const Offset(39.3444, 28.209), [
    Path()
      ..moveTo(0, 2.28)
      ..lineTo(2.74, 0)
      ..lineTo(37.62, 0)
      ..lineTo(39.45, 2.28)
      ..lineTo(33.06, 7.52)
      ..lineTo(4.1, 7.52)
      ..lineTo(0, 2.28)
      ..close(),
  ]);

  /// Segment b.
  static final _segB = PathArtPainter.layer(const Offset(68.7601, 32.0855), [
    Path()
      ..moveTo(4.1, 6.16)
      ..lineTo(11.4, 0)
      ..lineTo(12.54, 1.14)
      ..lineTo(7.3, 31.24)
      ..lineTo(3.42, 34.43)
      ..lineTo(0, 30.56)
      ..lineTo(4.1, 6.16)
      ..close(),
  ]);

  /// Segment c.
  static final _segC = PathArtPainter.layer(const Offset(62.1472, 69.7102), [
    Path()
      ..moveTo(0, 28.73)
      ..lineTo(4.33, 4.56)
      ..lineTo(9.81, 0)
      ..lineTo(12.31, 2.96)
      ..lineTo(7.07, 32.38)
      ..lineTo(4.79, 34.43)
      ..lineTo(0, 28.73)
      ..close(),
  ]);

  /// Segment d.
  static final _segD = PathArtPainter.layer(const Offset(26.8029, 100.266), [
    Path()
      ..moveTo(0, 5.24)
      ..lineTo(6.38, 0)
      ..lineTo(33.98, 0)
      ..lineTo(38.31, 5.24)
      ..lineTo(35.57, 7.52)
      ..lineTo(1.6, 7.52)
      ..lineTo(0, 5.24)
      ..close(),
  ]);

  /// Segment e.
  static final _segE = PathArtPainter.layer(const Offset(22.6984, 69.4822), [
    Path()
      ..moveTo(4.79, 3.88)
      ..lineTo(9.35, 0)
      ..lineTo(12.54, 3.65)
      ..lineTo(7.75, 30.1)
      ..lineTo(2.51, 34.43)
      ..lineTo(0, 31.47)
      ..lineTo(4.79, 3.88)
      ..close(),
  ]);

  /// Segment f.
  static final _segF = PathArtPainter.layer(const Offset(29.3112, 32.0855), [
    Path()
      ..moveTo(0, 30.56)
      ..lineTo(5.02, 2.74)
      ..lineTo(8.21, 0)
      ..lineTo(12.31, 4.79)
      ..lineTo(7.75, 30.33)
      ..lineTo(2.96, 34.2)
      ..lineTo(0, 30.56)
      ..close(),
  ]);

  /// Segment g.
  static final _segG = PathArtPainter.layer(const Offset(33.8717, 64.2375), [
    Path()
      ..moveTo(0, 3.88)
      ..lineTo(4.56, 0)
      ..lineTo(33.52, 0)
      ..lineTo(36.48, 3.88)
      ..lineTo(32.15, 7.52)
      ..lineTo(2.96, 7.52)
      ..lineTo(0, 3.88)
      ..close(),
  ]);

  /// The decimal point.
  static final _segDp = PathArtPainter.layer(const Offset(73.7767, 100.266), [
    Path()
      ..moveTo(8.44, 4.22)
      ..cubicTo(8.44, 6.55, 6.55, 8.44, 4.22, 8.44)
      ..cubicTo(1.89, 8.44, 0, 6.55, 0, 4.22)
      ..cubicTo(0, 1.89, 1.89, 0, 4.22, 0)
      ..cubicTo(6.55, 0, 8.44, 1.89, 8.44, 4.22)
      ..close(),
  ]);
}
