import 'package:flutter/widgets.dart';

import '../painting/base_component_painter.dart';
import '../painting/path_art.dart';

/// Draws an SPDT slide switch (an SS12D00) standing on its three pins, its
/// lever thrown to whichever side the `position` property says — the body of
/// `slide_switch_spdt.pdl`, which names it with `PAINTER slide_switch_spdt` and
/// declares everything else: pins, the property, physics.
///
/// The artwork is vector paths generated by the Flutter Da Vinci Figma plugin
/// from the "Slide Switch SPDT" frame in the *PinBench Parts* Figma file — one
/// layer per colour, each shifted to where that layer sits in the frame, the
/// lever drawn thrown to `a`. Redraw it there and regenerate rather than
/// hand-editing the coordinates.
class SlideSwitchSpdtPainter({final Map<String, dynamic>? properties, super.isOutline})
    extends BaseComponentPainter
    with PathArtPainter {
  // The `SIZE` the .pdl declares: the pins one hole pitch apart on the lattice
  // where its pins are, an SS12D00's real 2.54 mm, the body centred over them.
  static const width = 72.0;
  static const height = 88.0;
  static const componentSize = Size(width, height);

  /// How far the lever travels from `a` to `b`, in the frame's pixels.
  static const leverTravel = 12.991;

  /// The cover, base and lever; the pins below are what the wires reach for.
  @override
  Rect bodyRect(Size size) => const Rect.fromLTRB(7.15, 5.48, 62.9, 53);

  @override
  Size get designSize => componentSize;

  bool get _thrownToB => '${properties?['position']}' == 'B';

  @override
  List<PathArtLayer> get layers => [
    (_pins, const Color(0xFF8C8C8C)),
    (_thrownToB ? _leverAtB : _leverAtA, const Color(0xFF333333)),
    (_base, const Color(0xFFB8753F)),
    (_cover, const Color(0xFFBFBFBF)),
    (_coverLip, const Color(0xFFD9D9D9)),
  ];

  /// The lever thrown to b (right).
  static final _leverAtB = PathArtPainter.layer(const Offset(leverTravel, 0), _leverAtA);

  /// Flat blade pins: a, common, b.
  static final _pins = PathArtPainter.layer(const Offset(18.3284, 52), [
    Path()
      ..moveTo(0, 0)
      ..lineTo(3.44, 0)
      ..lineTo(3.44, 31.04)
      ..cubicTo(3.44, 31.57, 3.01, 32, 2.48, 32)
      ..lineTo(0.96, 32)
      ..cubicTo(0.43, 32, 0, 31.57, 0, 31.04)
      ..lineTo(0, 0)
      ..close(),
    Path()
      ..moveTo(15.95, 0)
      ..lineTo(19.39, 0)
      ..lineTo(19.39, 31.04)
      ..cubicTo(19.39, 31.57, 18.96, 32, 18.44, 32)
      ..lineTo(16.91, 32)
      ..cubicTo(16.38, 32, 15.95, 31.57, 15.95, 31.04)
      ..lineTo(15.95, 0)
      ..close(),
    Path()
      ..moveTo(32, 0)
      ..lineTo(35.44, 0)
      ..lineTo(35.44, 31.04)
      ..cubicTo(35.44, 31.57, 35.01, 32, 34.48, 32)
      ..lineTo(32.96, 32)
      ..cubicTo(32.43, 32, 32, 31.57, 32, 31.04)
      ..lineTo(32, 0)
      ..close(),
  ]);

  /// The lever, thrown to a (left).
  static final _leverAtA = PathArtPainter.layer(const Offset(23.7732, 5.4806), [
    Path()
      ..moveTo(0, 2.1)
      ..cubicTo(0, 0.94, 0.94, 0, 2.1, 0)
      ..lineTo(7.07, 0)
      ..cubicTo(8.23, 0, 9.17, 0.94, 9.17, 2.1)
      ..lineTo(9.17, 25.98)
      ..lineTo(0, 25.98)
      ..lineTo(0, 2.1)
      ..close(),
  ]);

  /// The moulded base.
  static final _base = PathArtPainter.layer(const Offset(7.6299, 45.3134), [
    Path()
      ..moveTo(0, 0.76)
      ..cubicTo(0, 0.34, 0.34, 0, 0.76, 0)
      ..lineTo(54.35, 0)
      ..cubicTo(54.77, 0, 55.12, 0.34, 55.12, 0.76)
      ..lineTo(55.12, 7.16)
      ..cubicTo(55.12, 7.59, 54.77, 7.93, 54.35, 7.93)
      ..lineTo(0.76, 7.93)
      ..cubicTo(0.34, 7.93, 0, 7.59, 0, 7.16)
      ..lineTo(0, 0.76)
      ..close(),
  ]);

  /// The metal cover and the two tabs folded over the base.
  static final _cover = PathArtPainter.layer(const Offset(7.1522, 29.0746), [
    Path()
      ..moveTo(0, 0.96)
      ..cubicTo(0, 0.43, 0.43, 0, 0.96, 0)
      ..lineTo(54.26, 0)
      ..cubicTo(54.78, 0, 55.21, 0.43, 55.21, 0.96)
      ..lineTo(55.21, 17.48)
      ..cubicTo(55.21, 18.01, 54.78, 18.44, 54.26, 18.44)
      ..lineTo(0.96, 18.44)
      ..cubicTo(0.43, 18.44, 0, 18.01, 0, 17.48)
      ..lineTo(0, 0.96)
      ..close(),
    Path()
      ..moveTo(8.6, 15.76)
      ..lineTo(16.24, 15.76)
      ..lineTo(16.24, 23.98)
      ..cubicTo(16.24, 24.29, 15.98, 24.55, 15.67, 24.55)
      ..lineTo(9.17, 24.55)
      ..cubicTo(8.85, 24.55, 8.6, 24.29, 8.6, 23.98)
      ..lineTo(8.6, 15.76)
      ..close(),
    Path()
      ..moveTo(40.31, 15.76)
      ..lineTo(47.95, 15.76)
      ..lineTo(47.95, 23.98)
      ..cubicTo(47.95, 24.29, 47.7, 24.55, 47.38, 24.55)
      ..lineTo(40.88, 24.55)
      ..cubicTo(40.57, 24.55, 40.31, 24.29, 40.31, 23.98)
      ..lineTo(40.31, 15.76)
      ..close(),
  ]);

  /// The cover's top edge.
  static final _coverLip = PathArtPainter.layer(const Offset(7.7253, 29.3612), [
    Path()
      ..moveTo(0, 0.57)
      ..cubicTo(0, 0.26, 0.26, 0, 0.57, 0)
      ..lineTo(53.49, 0)
      ..cubicTo(53.81, 0, 54.07, 0.26, 54.07, 0.57)
      ..lineTo(54.07, 0.76)
      ..cubicTo(54.07, 1.08, 53.81, 1.34, 53.49, 1.34)
      ..lineTo(0.57, 1.34)
      ..cubicTo(0.26, 1.34, 0, 1.08, 0, 0.76)
      ..lineTo(0, 0.57)
      ..close(),
  ]);
}
