import 'package:flutter/widgets.dart';

import '../../painting/base_component_painter.dart';
import '../../painting/path_art.dart';
import 'ir_receiver_art.dart';

/// Draws a VS1838B-style IR receiver standing on its legs, face on — the body
/// of `ir_receiver.pdl`, which names it with `PAINTER ir_receiver` and declares
/// everything else: pins and physics.
///
/// The artwork is vector paths generated by the Flutter Da Vinci Figma plugin
/// from the "IR Receiver" frame in the *PinBench Parts* Figma file — one layer
/// per colour, each shifted to where that layer sits in the frame. Redraw it
/// there and regenerate rather than hand-editing the coordinates.
class IrReceiverPainter({final Map<String, dynamic>? properties, super.isOutline})
    extends BaseComponentPainter
    with PathArtPainter {
  // The `SIZE` the .pdl declares: the legs' tips one hole pitch apart on the
  // lattice where its pins are, the shield centred over the middle one.
  static const width = 40.0;
  static const height = 72.0;
  static const componentSize = Size(width, height);

  /// The shield and its tabs; the legs below are what the pins reach for.
  @override
  Rect bodyRect(Size size) => const Rect.fromLTRB(0, 4, 40, 43);

  @override
  Size get designSize => componentSize;

  @override
  List<PathArtLayer> get layers => _layers;

  static final _layers = <PathArtLayer>[
    (IrReceiverArt.legs, const Color(0xFF8C8C8C)),
    (IrReceiverArt.shield, const Color(0xFFBFBFBF)),
    (IrReceiverArt.lens, const Color(0xFF2A2A2A)),
    (IrReceiverArt.shade, const Color(0xFFA6A6A6)),
    (IrReceiverArt.straps, const Color(0xFFD9D9D9)),
  ];
}
