import 'package:flutter/widgets.dart';

import '../../painting/base_component_painter.dart';
import '../../painting/path_art.dart';
import 'axial_diode_art.dart';

/// Which axial diode an [AxialDiodePainter] draws.
enum DiodeKind() {
  /// A 1N4007: black moulded DO-41 body, grey band.
  rectifier,

  /// A 1N4148: orange die in clear glass, black band.
  switching,

  /// A 1N5819: the rectifier's DO-41 body with a silver band.
  schottky,
}

/// Draws an axial diode standing on its leads, anode up and the cathode band
/// toward the bottom — the body of the `diode_*.pdl` parts, which name it with
/// `PAINTER diode_<part number>` and declare everything else: pins and physics.
///
/// The artwork is vector paths generated by the Flutter Da Vinci Figma plugin
/// from the "Diode 1N4007", "Diode 1N4148 glass" and "Diode 1N5819" frames in
/// the *PinBench Parts* Figma file — one layer per colour, each shifted to
/// where that layer sits in the frame. All three share the leads, the body's
/// box and the band's place, so they read as one family; only the materials
/// differ by [kind]. Redraw them there and regenerate rather than hand-editing
/// the coordinates.
class AxialDiodePainter(
  final DiodeKind kind, {
  final Map<String, dynamic>? properties,
  super.isOutline,
}) extends BaseComponentPainter with PathArtPainter {
  // The `SIZE` the .pdl declares: the leads' tips four hole pitches apart on
  // the lattice where its pins are, the body centred between them.
  static const width = 40.0;
  static const height = 72.0;
  static const componentSize = Size(width, height);

  /// The body; the leads beyond it are what the pins reach for.
  @override
  Rect bodyRect(Size size) => const Rect.fromLTWH(12.73, 17.02, 14.54, 37.97);

  @override
  Size get designSize => componentSize;

  @override
  List<PathArtLayer> get layers => switch (kind) {
    DiodeKind.rectifier => _rectifier,
    DiodeKind.switching => _switching,
    DiodeKind.schottky => _schottky,
  };

  static final _rectifier = <PathArtLayer>[
    (AxialDiodeArt.leads, const Color(0xFF8C8C8C)),
    (AxialDiodeArt.body, const Color(0xFF333333)),
    (AxialDiodeArt.cathodeBand, const Color(0xFF6A757E)),
  ];

  static final _switching = <PathArtLayer>[
    (AxialDiodeArt.leads, const Color(0xFF8C8C8C)),
    (AxialDiodeArt.glass, const Color(0xB2B8C4CA)),
    (AxialDiodeArt.glassCore, const Color(0xFFD9622B)),
    (AxialDiodeArt.cathodeBand, const Color(0xFF2A2A2A)),
  ];

  static final _schottky = <PathArtLayer>[
    (AxialDiodeArt.leads, const Color(0xFF8C8C8C)),
    (AxialDiodeArt.body, const Color(0xFF333333)),
    (AxialDiodeArt.cathodeBand, const Color(0xFFC8C8C8)),
  ];
}
