import 'package:flutter/widgets.dart';

import '../../painting/base_component_painter.dart';
import '../../painting/path_art.dart';
import 'ldr_art.dart';

/// Draws a light-dependent resistor (photoresistor) standing on its two leads —
/// the body of `ldr.pdl`, which names it with `PAINTER ldr` and declares
/// everything else: pins, properties, and the behaviour that sets its
/// resistance from the light on it.
///
/// The artwork is vector paths generated by the Flutter Da Vinci Figma plugin
/// from the "LDR" frame in the *PinBench Parts* Figma file — one layer per
/// colour, each shifted to where that layer sits in the frame. Redraw it there
/// and regenerate rather than hand-editing the coordinates.
class LdrPainter({final Map<String, dynamic>? properties, super.isOutline})
    extends BaseComponentPainter
    with PathArtPainter {
  // Same bounds as the ceramic capacitor, the `SIZE` the .pdl declares: the
  // disc centred over leads one hole pitch apart, ending where its pins are.
  static const width = 56.0;
  static const height = 52.0;
  static const componentSize = Size(width, height);

  /// The disc, which is all of the part except its leads.
  @override
  Rect bodyRect(Size size) => const Rect.fromLTWH(9.4, 0, 37.2, 32.3);

  @override
  Size get designSize => componentSize;

  @override
  List<PathArtLayer> get layers => _layers;

  static final _layers = <PathArtLayer>[
    (LdrArt.legs, const Color(0xFF818181)),
    (LdrArt.face, const Color(0xFFD7D7AA)),
    (LdrArt.track, const Color(0xFFAB552E)),
    (LdrArt.contacts, const Color(0xFFC8C3A0)),
  ];
}
