import 'package:flutter/widgets.dart';

import '../../painting/base_component_painter.dart';
import '../../painting/path_art.dart';
import 'electrolytic_capacitor_art.dart';

/// Draws an aluminium electrolytic capacitor standing on its leads, the
/// polarity stripe down the negative side — the body of
/// `capacitor_electrolytic.pdl`, which names it with
/// `PAINTER capacitor_electrolytic` and declares everything else: pins,
/// capacitance, physics.
///
/// The artwork is vector paths generated by the Flutter Da Vinci Figma plugin
/// from the "Electrolytic Capacitor" frame in the *PinBench Parts* Figma file —
/// one layer per colour, each shifted to where that layer sits in the frame.
/// Redraw it there and regenerate rather than hand-editing the coordinates.
class ElectrolyticCapacitorPainter({final Map<String, dynamic>? properties, super.isOutline})
    extends BaseComponentPainter
    with PathArtPainter {
  // The `SIZE` the .pdl declares: the leads' tips two hole pitches apart on
  // the lattice where its pins are, the can centred over them.
  static const width = 72.0;
  static const height = 88.0;
  static const componentSize = Size(width, height);

  /// The can; the leads below it are what the pins reach for.
  @override
  Rect bodyRect(Size size) => const Rect.fromLTWH(12.51, 2.98, 46.98, 76.94);

  @override
  Size get designSize => componentSize;

  @override
  List<PathArtLayer> get layers => _layers;

  static final _layers = <PathArtLayer>[
    (ElectrolyticCapacitorArt.leads, const Color(0xFF8C8C8C)),
    (ElectrolyticCapacitorArt.can, const Color(0xFF333333)),
    (ElectrolyticCapacitorArt.stripe, const Color(0xFF83888F)),
    (ElectrolyticCapacitorArt.stripeCrimp, const Color(0xFF7B8086)),
    (ElectrolyticCapacitorArt.rim, const Color(0xFF242424)),
    (ElectrolyticCapacitorArt.top, const Color(0xFFBFBFBF)),
  ];
}
