import 'package:flutter/widgets.dart';

import '../../painting/base_component_painter.dart';
import '../../painting/path_art.dart';
import 'transistor_art.dart';

/// Which transistor a [TransistorPainter] draws: the same TO-92 body, labelled
/// for its type and pin order.
enum TransistorKind() {
  npn,
  pnp,
  nmos,
  pmos,
}

/// Draws a transistor in a TO-92 package, flat face forward, standing on its
/// three legs — the body of the `transistor_*.pdl` parts, which name it with
/// `PAINTER transistor_<kind>` and declare everything else: pins and physics.
///
/// The artwork is vector paths generated by the Flutter Da Vinci Figma plugin
/// from the "Transistor NPN/PNP/NMOS/PMOS" frames in the *PinBench Parts*
/// Figma file — one layer per colour, each shifted to where that layer sits in
/// the frame. The body is shared; only the two label layers differ by [kind].
/// Redraw them there and regenerate rather than hand-editing the coordinates.
class TransistorPainter(
  final TransistorKind kind, {
  final Map<String, dynamic>? properties,
  super.isOutline,
}) extends BaseComponentPainter with PathArtPainter {
  // The `SIZE` the .pdl declares: the legs' tips one hole pitch apart on the
  // lattice where its pins are, the body centred over the middle one.
  static const width = 40.0;
  static const height = 72.0;
  static const componentSize = Size(width, height);

  /// The body; the legs below it are what the pins reach for.
  @override
  Rect bodyRect(Size size) => const Rect.fromLTRB(1.26, 5.6, 38.74, 52.2);

  @override
  Size get designSize => componentSize;

  @override
  List<PathArtLayer> get layers => switch (kind) {
    TransistorKind.npn => _npn,
    TransistorKind.pnp => _pnp,
    TransistorKind.nmos => _nmos,
    TransistorKind.pmos => _pmos,
  };

  static List<PathArtLayer> _withLabels(List<Path> label, List<Path> pins) => [
    (TransistorArt.legs, const Color(0xFF8C8C8C)),
    (TransistorArt.rim, const Color(0xFF595959)),
    (TransistorArt.dark, const Color(0xFF333333)),
    (label, const Color(0xFFE3E3E3)),
    (pins, const Color(0xFF666666)),
  ];

  static final _npn = _withLabels(TransistorArt.npnLabel, TransistorArt.npnPins);
  static final _pnp = _withLabels(TransistorArt.pnpLabel, TransistorArt.pnpPins);
  static final _nmos = _withLabels(TransistorArt.nmosLabel, TransistorArt.nmosPins);
  static final _pmos = _withLabels(TransistorArt.pmosLabel, TransistorArt.pmosPins);
}
