import 'package:flutter/widgets.dart';

import '../../painting/base_component_painter.dart';
import '../../painting/path_art.dart';
import '../../painting/part_text.dart';
import 'transistor_art.dart';

/// Which transistor a [TransistorPainter] draws: the same TO-92 body, labelled
/// for its type and pin order.
enum TransistorKind() {
  npn,
  pnp,
  nmos,
  pmos,
}

/// Draws a transistor in a TO-92 package, flat face forward, standing on its
/// three legs — the body of the `transistor_*.pdl` parts, which name it with
/// `PAINTER transistor_<kind>` and declare everything else: pins and physics.
///
/// The body is vector paths generated by the Flutter Da Vinci Figma plugin
/// from the "Transistor NPN" frame in the *PinBench Parts* Figma file — one
/// layer per colour, each shifted to where it sits in the frame — and is the
/// same for every [kind]. What differs is printed on it as text.
class TransistorPainter(
  final TransistorKind kind, {
  final Map<String, dynamic>? properties,
  super.isOutline,
}) extends BaseComponentPainter with PathArtPainter {
  // The `SIZE` the .pdl declares: the legs' tips one hole pitch apart on the
  // lattice where its pins are, the body centred over the middle one.
  static const width = 40.0;
  static const height = 72.0;
  static const componentSize = Size(width, height);

  /// The body; the legs below it are what the pins reach for.
  @override
  Rect bodyRect(Size size) => const Rect.fromLTRB(1.26, 5.6, 38.74, 52.2);

  @override
  Size get designSize => componentSize;

  @override
  List<PathArtLayer> get layers => _layers;

  /// The same body for every kind; what differs is printed on it.
  static final _layers = <PathArtLayer>[
    (TransistorArt.legs, const Color(0xFF8C8C8C)),
    (TransistorArt.rim, const Color(0xFF595959)),
    (TransistorArt.dark, const Color(0xFF333333)),
  ];

  /// The type on the flat face, and under it each leg's letter, left to right.
  @override
  void paintText(Canvas canvas) {
    final (label, legs) = switch (kind) {
      TransistorKind.npn => (_n, 'CBE'),
      TransistorKind.pnp => (_p, 'EBC'),
      TransistorKind.nmos => (_nmos, 'DGS'),
      TransistorKind.pmos => (_pmos, 'SGD'),
    };
    label.paint(canvas, const Offset(20, 31.1));
    for (var i = 0; i < 3; i++) {
      PartText(legs[i], capHeight: 4.6, color: _pinInk).paint(canvas, Offset(_letterX[i], 45.1));
    }
  }

  static const _labelInk = Color(0xFFE3E3E3);
  static const _pinInk = Color(0xFF666666);
  static const _letterX = [9.5, 20.0, 30.5];
  static const _n = PartText('N', capHeight: 13, color: _labelInk);
  static const _p = PartText('P', capHeight: 13, color: _labelInk);
  static const _nmos = PartText('NMOS', capHeight: 7.2, color: _labelInk, maxWidth: 26);
  static const _pmos = PartText('PMOS', capHeight: 7.2, color: _labelInk, maxWidth: 26);
}
