import 'package:flutter/widgets.dart';

import '../../painting/base_component_painter.dart';
import '../../painting/path_art.dart';
import '../../painting/part_text.dart';
import 'cr2032_art.dart';

/// Draws a CR2032 coin cell in its holder, red (+) lead up, black (−) down —
/// the body of `cr2032.pdl`, which names it with `PAINTER cr2032` and declares
/// everything else: pins, properties, physics.
///
/// The artwork is vector paths generated by the Flutter Da Vinci Figma plugin
/// from the "Coin Cell CR2032" frame in the *PinBench Parts* Figma file — one
/// layer per colour, each shifted to where that layer sits in the frame.
/// Redraw it there and regenerate rather than hand-editing the coordinates.
class Cr2032Painter({final Map<String, dynamic>? properties, super.isOutline})
    extends BaseComponentPainter
    with PathArtPainter {
  // The `SIZE` the .pdl declares: the holder upright, its lead tips thirteen
  // hole pitches apart on the connection lattice where its pins are.
  static const width = 136.0;
  static const height = 200.0;
  static const componentSize = Size(width, height);

  /// The holder; the lead tips beyond it are what the pins reach for.
  @override
  Rect bodyRect(Size size) => const Rect.fromLTRB(1.6, 20.1, 134.4, 191.7);

  @override
  Size get designSize => componentSize;

  @override
  List<PathArtLayer> get layers => _layers;

  static final _layers = <PathArtLayer>[
    (Cr2032Art.leads, const Color(0xFF8C8C8C)),
    (Cr2032Art.holder, const Color(0xFF333333)),
    (Cr2032Art.cellEdge, const Color(0xFF5E5E5E)),
    (Cr2032Art.metal, const Color(0xFFBFBFBF)),
    (Cr2032Art.contactShadow, const Color(0xFF7F7F7F)),
    (Cr2032Art.highlights, const Color(0xFFDDDDDD)),
    (Cr2032Art.plusBoot, const Color(0xFFA12C25)),
    (Cr2032Art.plusCollar, const Color(0xFF711F1A)),
    (Cr2032Art.minusCollar, const Color(0xFF242424)),
    (Cr2032Art.plus, _print),
  ];

  /// The legend on the cell face, under its plus sign.
  @override
  void paintText(Canvas canvas) {
    for (final (line, y) in _legend) {
      line.paint(canvas, Offset(68, y));
    }
  }

  static const _print = Color(0xFFFFFFFF);
  static const _legend = [
    (PartText('COIN BATTERY', capHeight: 10, color: _print, maxWidth: 99), 100.6),
    (PartText('CR 2032', capHeight: 10, color: _print), 119.4),
    (PartText('3.0V', capHeight: 10, color: _print), 138.2),
  ];
}
