import 'package:flutter/widgets.dart';

import '../../painting/base_component_painter.dart';
import '../../painting/path_art.dart';
import '../../painting/part_text.dart';
import 'to220_art.dart';

/// Which part a [To220Painter] draws: the same TO-220 package, labelled for
/// its type and pin order.
enum To220Kind() {
  powerNmos,
  powerPmos,
  tip120,
}

/// Draws a power transistor in a TO-220 package, tab up, standing on its three
/// legs — the body of the `power_nmos`, `power_pmos` and `tip120` parts, which
/// name it with `PAINTER to220_<kind>` and declare everything else: pins and
/// physics.
///
/// The package is vector paths generated by the Flutter Da Vinci Figma plugin
/// from the "Power NMOS" frame in the *PinBench Parts* Figma file — one layer
/// per colour, each shifted to where it sits in the frame — and is the same
/// for every [kind]. What differs is printed on it as text.
class To220Painter(final To220Kind kind, {final Map<String, dynamic>? properties, super.isOutline})
    extends BaseComponentPainter
    with PathArtPainter {
  // The `SIZE` the .pdl declares: the legs' tips one hole pitch apart on the
  // lattice where its pins are, the package centred over the middle one.
  static const width = 72.0;
  static const height = 88.0;
  static const componentSize = Size(width, height);

  /// The package; the legs below it are what the pins reach for.
  @override
  Rect bodyRect(Size size) => const Rect.fromLTRB(12.06, 0, 59.94, 60.4);

  @override
  Size get designSize => componentSize;

  @override
  List<PathArtLayer> get layers => _layers;

  /// The same package for every kind; what differs is printed on it.
  static final _layers = <PathArtLayer>[
    (To220Art.legs, const Color(0xFF8C8C8C)),
    (To220Art.body, const Color(0xFF333333)),
    (To220Art.band, const Color(0xFF242424)),
    (To220Art.bandEdge, const Color(0xFF5C5C5C)),
    (To220Art.tab, const Color(0xFFBFBFBF)),
    (To220Art.tabLip, const Color(0xFFD9D9D9)),
    (To220Art.holeShadow, const Color(0xFF999999)),
  ];

  /// The part on the body, and under it each leg's letter, left to right.
  @override
  void paintText(Canvas canvas) {
    final (label, legs) = switch (kind) {
      To220Kind.powerNmos => (_nmos, 'GDS'),
      To220Kind.powerPmos => (_pmos, 'GDS'),
      To220Kind.tip120 => (_tip120, 'BCE'),
    };
    label.paint(canvas, const Offset(36, 38));
    for (var i = 0; i < 3; i++) {
      PartText(legs[i], capHeight: 4.5, color: _pinInk).paint(canvas, Offset(20.0 + 16 * i, 54.5));
    }
  }

  static const _labelInk = Color(0xFFE3E3E3);
  static const _pinInk = Color(0xFF666666);
  static const _nmos = PartText('NMOS', capHeight: 9.3, color: _labelInk, maxWidth: 40);
  static const _pmos = PartText('PMOS', capHeight: 9.3, color: _labelInk, maxWidth: 40);
  static const _tip120 = PartText('TIP120', capHeight: 9, color: _labelInk, maxWidth: 40);
}
