import 'package:flutter/widgets.dart';

import '../../painting/base_component_painter.dart';
import '../../painting/path_art.dart';
import 'to220_art.dart';

/// Which part a [To220Painter] draws: the same TO-220 package, labelled for
/// its type and pin order.
enum To220Kind() {
  powerNmos,
  powerPmos,
  tip120,
}

/// Draws a power transistor in a TO-220 package, tab up, standing on its three
/// legs — the body of the `power_nmos`, `power_pmos` and `tip120` parts, which
/// name it with `PAINTER to220_<kind>` and declare everything else: pins and
/// physics.
///
/// The artwork is vector paths generated by the Flutter Da Vinci Figma plugin
/// from the "Power NMOS", "Power PMOS" and "TIP120" frames in the *PinBench
/// Parts* Figma file — one layer per colour, each shifted to where that layer
/// sits in the frame. The package is shared; only the two label layers differ
/// by [kind]. Redraw them there and regenerate rather than hand-editing the
/// coordinates.
class To220Painter(final To220Kind kind, {final Map<String, dynamic>? properties, super.isOutline})
    extends BaseComponentPainter
    with PathArtPainter {
  // The `SIZE` the .pdl declares: the legs' tips one hole pitch apart on the
  // lattice where its pins are, the package centred over the middle one.
  static const width = 72.0;
  static const height = 88.0;
  static const componentSize = Size(width, height);

  /// The package; the legs below it are what the pins reach for.
  @override
  Rect bodyRect(Size size) => const Rect.fromLTRB(12.06, 0, 59.94, 60.4);

  @override
  Size get designSize => componentSize;

  @override
  List<PathArtLayer> get layers => switch (kind) {
    To220Kind.powerNmos => _powerNmos,
    To220Kind.powerPmos => _powerPmos,
    To220Kind.tip120 => _tip120,
  };

  static List<PathArtLayer> _withLabels(List<Path> label, List<Path> pins) => [
    (To220Art.legs, const Color(0xFF8C8C8C)),
    (To220Art.body, const Color(0xFF333333)),
    (To220Art.band, const Color(0xFF242424)),
    (To220Art.bandEdge, const Color(0xFF5C5C5C)),
    (To220Art.tab, const Color(0xFFBFBFBF)),
    (To220Art.tabLip, const Color(0xFFD9D9D9)),
    (To220Art.holeShadow, const Color(0xFF999999)),
    (label, const Color(0xFFE3E3E3)),
    (pins, const Color(0xFF666666)),
  ];

  static final _powerNmos = _withLabels(To220Art.nmosLabel, To220Art.gdsPins);
  static final _powerPmos = _withLabels(To220Art.pmosLabel, To220Art.gdsPins);
  static final _tip120 = _withLabels(To220Art.tip120Label, To220Art.bcePins);
}
