import 'package:flutter/widgets.dart';

import '../../painting/base_component_painter.dart';
import '../../painting/grid_system.dart';
import '../../painting/path_art.dart';
import 'battery_9v_art.dart';

/// Draws a 9 V PP3 battery with its snap clip, leads exiting to the left — the
/// body of `battery_9v.pdl`, which names it with `PAINTER battery_9v` and
/// declares everything else: pins, properties, physics.
///
/// The artwork is vector paths generated by the Flutter Da Vinci Figma plugin
/// from the "Battery 9V" frame in the *PinBench Parts* Figma file — one layer
/// per colour, each shifted to where that layer sits in the frame. Redraw it
/// there and regenerate rather than hand-editing the coordinates.
class Battery9vPainter({final Map<String, dynamic>? properties, super.isOutline})
    extends BaseComponentPainter
    with PathArtPainter {
  // The PP3 case is 48.5 × 26.5 mm; the frame is rounded to whole hole
  // pitches (19 × 10), the `SIZE` the .pdl declares, so both lead tips land on
  // the connection lattice where its pins are.
  static const width = 19 * GridSystem.pitch;
  static const height = 10 * GridSystem.pitch;
  static const componentSize = Size(width, height);

  /// The case and clip; the leads hang off it to the ports.
  @override
  Rect bodyRect(Size size) => const Rect.fromLTRB(24, 8, width, 152);

  @override
  Size get designSize => componentSize;

  @override
  List<PathArtLayer> get layers => _layers;

  static final _layers = <PathArtLayer>[
    (Battery9vArt.copper, const Color(0xFFCB804F)),
    (Battery9vArt.polarityRings, const Color(0xFFAB6F48)),
    (Battery9vArt.dark, const Color(0xFF2D2D2D)),
    (Battery9vArt.terminalShadow, const Color(0xFF818181)),
    (Battery9vArt.terminalFace, const Color(0xFFB1B1B1)),
    (Battery9vArt.redLead, const Color(0xFFA5161F)),
    (Battery9vArt.label, const Color(0xFFD8D8D8)),
  ];
}
