import 'package:flutter/widgets.dart';

import '../../models/part_model.dart';
import '../../models/port_model.dart';
import '../../painting/base_component_painter.dart';
import '../../painting/part_text.dart';
import '../../painting/path_art.dart';
import '../../painting/port_provider.dart';
import 'ir_remote_art.dart';

/// Draws the mini IR remote, each of its twenty buttons pressable on the
/// canvas: [regionAt] names the button under the pointer, and the one held
/// down — [ComponentProps.pressedRegion] — is drawn pressed in.
///
/// A press is what the simulation acts on: the engine sends that button's NEC
/// code (see `IrRemoteKeys`) to every IR receiver in the circuit. The remote
/// has no pins; it reaches the receivers the way a real one does, through the
/// air.
///
/// The artwork is vector paths generated by the Flutter Da Vinci Figma plugin
/// from the "IR Remote" frame in the *PinBench Parts* Figma file — one layer
/// per colour. Redraw it there and regenerate rather than hand-editing the
/// coordinates; [_buttons] is the grid that drew them.
class IrRemotePainter({final Map<String, dynamic>? properties, super.isOutline})
    extends BaseComponentPainter
    with PathArtPainter, PortProvider {
  // Redrawn when its labels' font arrives; see `PartText`.
  this : super(repaint: PartText.fontsChanged);

  // The real remote's size: 39 by 86 mm.
  static const width = 248.0;
  static const height = 544.0;
  static const componentSize = Size(width, height);

  // The button grid, in the frame's pixels: reference-photo positions scaled
  // by 248/220, as the Figma frame was built.
  static const _scale = 248 / 220;
  static const _columns = [294, 356, 418];
  static const _rows = [131, 187, 244, 300, 357, 414, 470];
  static const _radius = 24 * _scale;

  /// Each button's id — the key `IrRemoteKeys.commands` sends it under — and
  /// its place on the grid.
  static const _buttons = <(String, int, int)>[
    ('power', 0, 0), ('menu', 2, 0), //
    ('test', 0, 1), ('plus', 1, 1), ('back', 2, 1),
    ('previous', 0, 2), ('play', 1, 2), ('next', 2, 2),
    ('0', 0, 3), ('minus', 1, 3), ('c', 2, 3),
    ('1', 0, 4), ('2', 1, 4), ('3', 2, 4),
    ('4', 0, 5), ('5', 1, 5), ('6', 2, 5),
    ('7', 0, 6), ('8', 1, 6), ('9', 2, 6),
  ];

  /// None: it reaches the receivers through the air, not through a wire.
  @override
  List<ComponentPort> getPorts() => const [];

  static Offset _centre(int column, int row) =>
      Offset((_columns[column] - 248) * _scale, (_rows[row] - 70) * _scale);

  @override
  String? regionAt(Offset localPosition, Size size) {
    final design = Offset(
      localPosition.dx * width / size.width,
      localPosition.dy * height / size.height,
    );
    for (final (id, column, row) in _buttons) {
      if ((design - _centre(column, row)).distance <= _radius) return id;
    }
    return null;
  }

  @override
  Size get designSize => componentSize;

  @override
  List<PathArtLayer> get layers => _layers;

  static final _layers = <PathArtLayer>[
    (IrRemoteArt.body, const Color(0xFFF7F7F7)),
    (IrRemoteArt.ink, const Color(0xFF1F1F1F)),
    (IrRemoteArt.red, const Color(0xFFE52421)),
    (IrRemoteArt.white, const Color(0xFFFFFFFF)),
  ];

  /// The labels on the keys that have words rather than icons.
  @override
  void paintText(Canvas canvas) {
    for (final (id, column, row) in _buttons) {
      _labels[id]?.paint(canvas, _centre(column, row));
    }
  }

  static const _ink = Color(0xFF1F1F1F);
  static final _labels = <String, PartText>{
    for (final digit in '0123456789'.split('')) digit: PartText(digit, capHeight: 19, color: _ink),
    'c': const PartText('C', capHeight: 19, color: _ink),
    'test': const PartText('TEST', capHeight: 11, color: _ink, maxWidth: 40),
    'menu': const PartText('MENU', capHeight: 11, color: Color(0xFFE52421), maxWidth: 40),
  };

  String? get _pressed => properties?[ComponentProps.pressedRegion] as String?;

  @override
  void paintOverlay(Canvas canvas) {
    for (final (id, column, row) in _buttons) {
      if (id != _pressed) continue;
      // Pressed in: the button's face shaded, as if it has sunk into the case.
      canvas.drawCircle(_centre(column, row), _radius, Paint()..color = const Color(0x40000000));
    }
  }

  // A built-in part, not drawn through `DSLComponentPainter`, so nothing else
  // tells the canvas a press changed how it looks.
  @override
  bool shouldRepaintComponent(covariant IrRemotePainter oldDelegate) =>
      oldDelegate._pressed != _pressed;
}
