import 'package:flutter/widgets.dart';

import '../../painting/base_component_painter.dart';
import '../../painting/path_art.dart';
import 'slide_switch_spdt_art.dart';

/// Draws an SPDT slide switch (an SS12D00) standing on its three pins, its
/// lever thrown to whichever side the `position` property says — the body of
/// `slide_switch_spdt.pdl`, which names it with `PAINTER slide_switch_spdt` and
/// declares everything else: pins, the property, physics.
///
/// The artwork is vector paths generated by the Flutter Da Vinci Figma plugin
/// from the "Slide Switch SPDT" frame in the *PinBench Parts* Figma file — one
/// layer per colour, each shifted to where that layer sits in the frame, the
/// lever drawn thrown to `a`. Redraw it there and regenerate rather than
/// hand-editing the coordinates.
class SlideSwitchSpdtPainter({final Map<String, dynamic>? properties, super.isOutline})
    extends BaseComponentPainter
    with PathArtPainter {
  // The `SIZE` the .pdl declares: the pins one hole pitch apart on the lattice
  // where its pins are, an SS12D00's real 2.54 mm, the body centred over them.
  static const width = 72.0;
  static const height = 88.0;
  static const componentSize = Size(width, height);

  /// How far the lever travels from `a` to `b`, in the frame's pixels.
  static const leverTravel = 12.991;

  /// The cover, base and lever; the pins below are what the wires reach for.
  @override
  Rect bodyRect(Size size) => const Rect.fromLTRB(7.15, 5.48, 62.9, 53);

  @override
  Size get designSize => componentSize;

  bool get _thrownToB => '${properties?['position']}' == 'B';

  @override
  List<PathArtLayer> get layers => _thrownToB ? _atB : _atA;

  // One fixed list per lever position, so each is recorded once (see
  // [PathArtPainter]) rather than rebuilt on every paint.
  static final _atA = _withLever(SlideSwitchSpdtArt.leverAtA);
  static final _atB = _withLever(
    PathArtPainter.layer(const Offset(leverTravel, 0), SlideSwitchSpdtArt.leverAtA),
  );

  static List<PathArtLayer> _withLever(List<Path> lever) => [
    (SlideSwitchSpdtArt.pins, const Color(0xFF8C8C8C)),
    (lever, const Color(0xFF333333)),
    (SlideSwitchSpdtArt.base, const Color(0xFFB8753F)),
    (SlideSwitchSpdtArt.cover, const Color(0xFFBFBFBF)),
    (SlideSwitchSpdtArt.coverLip, const Color(0xFFD9D9D9)),
  ];
}
