import 'package:flutter/widgets.dart';

import '../../painting/base_component_painter.dart';
import '../../painting/path_art.dart';
import '../../models/part_properties.dart';
import 'seven_segment_art.dart';

/// Draws a 0.56-inch common-cathode 7-segment display, each segment lit as
/// brightly as the current through it — the body of `seven_segment.pdl`, which
/// names it with `PAINTER seven_segment` and declares everything else: the ten
/// pins, the eight-die physics, and the per-segment state this reads.
///
/// The artwork is vector paths generated by the Flutter Da Vinci Figma plugin
/// from the "7-Segment Display" frame in the *PinBench Parts* Figma file —
/// one layer per segment, so each can light on its own. Redraw it there and
/// regenerate rather than hand-editing the coordinates. The glow is drawn in
/// code, because it is state rather than artwork.
class SevenSegmentPainter({final Map<String, dynamic>? properties, super.isOutline})
    extends BaseComponentPainter
    with PathArtPainter {
  // The `SIZE` the .pdl declares: two rows of five pins one hole pitch apart,
  // six pitches between the rows — a real 0.56-inch display's footprint.
  static const width = 104.0;
  static const height = 136.0;
  static const componentSize = Size(width, height);

  static const _unlit = Color(0xFFB2B2B2);
  static const _lit = Color(0xFFFF3B30);

  /// The body; the pins are under it, as on the real part.
  @override
  Rect bodyRect(Size size) => const Rect.fromLTWH(12.21, 8.14, 79.8, 119.9);

  @override
  Size get designSize => componentSize;

  @override
  List<PathArtLayer> get layers => _layers;

  static final _layers = <PathArtLayer>[
    (SevenSegmentArt.body, const Color(0xFF3D4042)),
    (SevenSegmentArt.pinMarks, const Color(0xFF515355)),
    for (final (_, paths) in _segments) (paths, _unlit),
  ];

  /// Each segment's paths under the pin — and state — id it answers to.
  static final _segments = <(String, List<Path>)>[
    ('a', SevenSegmentArt.segA),
    ('b', SevenSegmentArt.segB),
    ('c', SevenSegmentArt.segC),
    ('d', SevenSegmentArt.segD),
    ('e', SevenSegmentArt.segE),
    ('f', SevenSegmentArt.segF),
    ('g', SevenSegmentArt.segG),
    ('dp', SevenSegmentArt.segDp),
  ];

  /// A segment's brightness, 0–1, as the `led_array` logic last wrote it.
  double _level(String segment) => properties.level(segment);

  @override
  void paintOverlay(Canvas canvas) {
    for (final (segment, paths) in _segments) {
      final level = _level(segment);
      if (level == 0) continue;
      final glow = Paint()
        ..color = _lit.withValues(alpha: 0.6 * level)
        ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 3);
      final face = Paint()..color = Color.lerp(_unlit, _lit, 0.4 + 0.6 * level)!;
      for (final path in paths) {
        canvas.drawPath(path, glow);
        canvas.drawPath(path, face);
      }
    }
  }
}
